version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: